### PR TITLE
Localization Updated

### PR DESCRIPTION
**Pull request by Shaswat27**
Required packages added in the same folder.
Readme updated.

### CODE REVIEW

**Comment by shivamvats** [comment]
@Shaswat27 What exactly did you change?
Too many files/lines have been changed.

**Comment by Shaswat27** [comment]
@shivamvats The entire package has been be updated and the two other required packages have been added.

**Comment by shivamvats** [comment]
Please split the commits into multiple commits. Each commit should do only one thing and explain what it does. It is very difficult for me to review this PR like this,

**Comment by Shaswat27** [comment]
@shivamvats Most of the changes are in the package's update itself. The only files I have changed are robot_localization/launch/filter.launch , robot_localization/src/odometry_gps.cpp and robot_localization/src/imu_covariance.cpp.
Rest of the two packages are standard packages required by the updated robot_localization package.

**Comment by shivamvats** [comment]
Then, there should be at least four commits. How am I supposed to review 6000 lines all put in one commit?

**Comment by Shaswat27** [comment]
Alright, I'll split the commits commits tomorrow. (travelling)

On 15-Dec-2015 1:47 pm, Shivam Vats <notifications@github.com> wrote:

Then, there should be at least four commits. How am I supposed to review 6000 lines all put in one commit?

**Comment by Shaswat27** [comment]
@shivamvats I'll create a new pull request as per suggested.

**Comment by shivamvats** [comment]
@Shaswat27 Please do it ASAP. We are facing problems in waypoint navigation. Hopefully, this will be an improvement.

**Pull request closed without merging**
