### PR TITLE
Created a sample test file in the lane_detector package

### PR DESCRIPTION
**Pull request by todivasudha**

### CODE REVIEW

**Comment by krishna95** [comment]
@todivasudha Also remove the file CMakeLists.txt~. Its a redundant file and add the regex corresponding to it in your gitignore.

**Comment by shivamvats** [comment]
@todivasudha Is `gtest` supposed to be in the repo or installed in our system?

**Comment by todivasudha** [comment]
@shivamvats gtest is already included in catkin so nothing is to be installed for it.

**Comment by krishna95** [comment]
@todivasudha This is not the branch to merge the commits. Further, [in this hpp] (https://github.com/AGV-IIT-KGP/eklavya-2015/blob/igvc_nav/perception/lane_detector/include/laneDetector.hpp) add the necessary function u are using and make the necessary changes in getlanebinary.cpp function

**Pull request closed without merging**
