### PR TITLE
Move base

### PR DESCRIPTION
**Pull request by chatrasen**

### CODE REVIEW

**Comment by shivamvats** [comment]
@chatrasen Could you elaborate on the changes you have made? In every PR always explain the changes in a comment.

**Comment by shivamvats** [comment]
@chatrasen Why does this look similar to #63

**Comment by chatrasen** [comment]
Apart the from the conclusions we can make from the commits, I had also written certain comments. Anyway, what the fourth commit (..incorporated in waypoint selector....) changed is deleted the waypoint navigator package.
Also, The cmake specified in the third commit is the one inside the high_level_planner package

**Comment by chatrasen** [comment]
I am closing this one as it is inappropriate 
Closed #64

**Pull request closed without merging**
